[package]
name = "merhaba_cargo_dunyasi"
version = "0.1.0"
edition = "2021"
edittion = "Orguntay"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
